[project]
name = "url-cralwer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "bs4>=0.0.2",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
]
